### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mika-f** [mika-f/nekodoc#1]
* [ ] support swc
* [ ] support esbuild watch mode
* [ ] support rollup (for production build)
* [ ] support hot reload (react-refresh?)
* [x] support linux machine (build failed in Linux (Vercel))
* [ ] support GA4 plugin
* [ ] support GTags plugin
* [x] support development/production configuration
* [x] support TypeScript configuration
